insert into customer (name, lastname, email, created_at) values ('Diego', 'Scifo', 'dscifo@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Sol', 'Mauna', 'sol@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Pedro', 'Gómez', 'pgomez@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Pablo', 'Almeida', 'palmeida@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Walter', 'White', 'wwhite@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Koji', 'Kabuto', 'kkabuto@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Frodo', 'Bolsón', 'fbolson@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Bilbo', 'Bolsón', 'bbolson@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Diego', 'Rozo', 'drozo@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Leo', 'Suárez', 'lsuarez@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Martín', 'Soto', 'msoto@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Mariano', 'Cialone', 'mcialone@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Jhon', 'Rambo', 'jrambo@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Mia', 'Khalifa', 'mkhalifa@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Giancarlo', 'Espósito', 'gesposito@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Wanda', 'Nara', 'wnara@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Lio', 'Messi', 'lmessi@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Liu', 'Kang', 'lkang@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Jonny', 'Cage', 'jcage@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Kill', 'Bill', 'kbill@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Tony', 'Vallelonga', 'tvallelonga@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Don', 'Shirley', 'dshirley@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Ray', 'Liotta', 'rliotta@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Robert', 'De Niro', 'rdeniro@mail.com', '2020-08-04');
insert into customer (name, lastname, email, created_at) values ('Joe', 'Pesci', 'jpesci@mail.com', '2020-08-04');

